using System.Text;

namespace RoslynKit;

/// <summary>
/// Renders the generated runtime command reference from the built-in command registry.
/// </summary>
public static class CommandReferenceMarkdown
{
    public const string RelativePath = "docs/agents/roslynkit-command-reference.md";

    /// <summary>
    /// Renders deterministic markdown for the registered command names, usage strings, and options.
    /// </summary>
    public static string Render()
    {
        var builder = new StringBuilder();
        AppendLine(builder, "# RoslynKit Command Reference");
        AppendLine(builder);
        AppendLine(builder, "<!-- This file is generated by `dotnet run --file .\\tools\\RoslynKit.CommandDocs.cs -- --write`. Do not edit by hand. -->");
        AppendLine(builder);
        AppendLine(builder, "Source: `src/RoslynKit/BuiltinCommandRegistry.cs`");
        AppendLine(builder);
        AppendLine(builder, "This reference lists the runtime command metadata used by parser binding and help output. Agent routing guidance remains in [.agents/skills/roslynkit/SKILL.md](../../.agents/skills/roslynkit/SKILL.md) and [.agents/skills/roslynkit-dev/SKILL.md](../../.agents/skills/roslynkit-dev/SKILL.md); planning coverage remains in [docs/roslyn-lsp-commands.md](../roslyn-lsp-commands.md).");
        AppendLine(builder);
        AppendLine(builder, "## Commands");
        AppendLine(builder);

        foreach (var command in BuiltinCommandRegistry.Commands)
        {
            builder.Append("- ").Append(CodeSpan(command.Name)).Append(": ").Append(command.Description);
            AppendLine(builder);
        }

        foreach (var command in BuiltinCommandRegistry.Commands)
        {
            AppendLine(builder);
            builder.Append("## ").Append(CodeSpan(command.Name));
            AppendLine(builder);
            AppendLine(builder);
            AppendLine(builder, command.Description);
            AppendLine(builder);
            AppendLine(builder, "### Usage");
            AppendLine(builder);
            AppendLine(builder, "```powershell");
            foreach (var usage in command.Usage)
            {
                AppendLine(builder, usage);
            }

            AppendLine(builder, "```");
            AppendLine(builder);
            AppendLine(builder, "### Options");
            AppendLine(builder);

            if (command.Options.Count == 0)
            {
                AppendLine(builder, "No options.");
                continue;
            }

            foreach (var option in command.Options)
            {
                AppendOption(builder, option);
            }
        }

        return builder.ToString();
    }

    private static void AppendOption(StringBuilder builder, OptionSpec option)
    {
        builder.Append("- ").Append(CodeSpan($"--{option.LongName}"));
        if (option.ShortName is { } shortName)
        {
            builder.Append(" / ").Append(CodeSpan($"-{shortName}"));
        }

        if (option.ValueName is { } valueName)
        {
            builder.Append(' ').Append(CodeSpan($"<{valueName}>"));
        }

        if (option.Required)
        {
            builder.Append(" (required)");
        }

        builder.Append(": ").Append(option.Description);
        AppendLine(builder);
    }

    private static string CodeSpan(string value)
    {
        return value.Contains('`') ? $"`` {value} ``" : $"`{value}`";
    }

    private static void AppendLine(StringBuilder builder, string value = "")
    {
        builder.Append(value);
        builder.Append('\n');
    }
}
